name = "spectrum2-mcp-worker-2"
main = "src/worker-2.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
WORKER_TYPE = "WORKER_2"

# Enable logging
[observability]
enabled = true

# KV namespace for caching
[[kv_namespaces]]
binding = "SPECTRUM_CACHE"
id = "c5f2824b87cd4081bba0a8daa18edadb"
preview_id = "c5f2824b87cd4081bba0a8daa18edadb"