name = "spectrum2-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "SPECTRUM_CACHE"
# id = "your-actual-namespace-id"
# preview_id = "your-actual-preview-id"