name = "spectrum2-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# KV namespace for caching
[[kv_namespaces]]
binding = "SPECTRUM_CACHE"
id = "c5f2824b87cd4081bba0a8daa18edadb"
preview_id = "c5f2824b87cd4081bba0a8daa18edadb"